---
global:
templates:
- '/etc/alertmanager/template/*.tmpl'
route:
  repeat_interval: 1m
  receiver: operations-team

receivers:
- name: 'operations-team'
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
    channel: '#xalert'
    send_resolved: true
